# fly.toml app configuration file generated for esm-ay-ms on 2024-10-06T07:57:54+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'esm-ay-ms'
primary_region = 'syd'

[env]
  DISABLE_COMPRESSION = "false"
  #  Disable generating source map for build JS/CSS files, default is false. 
  DISABLE_SOURCEMAP = "false"
  #  Minify the build JS/CSS files, default is true.
  MINIFY = "true" 
  # The log level, available values are ["debug", "info", "warn", "error"], default is "info".
  LOG_LEVEL = "info" 
  #  The global NPM registry, default is "https # //registry.npmjs.org/".
  NPM_REGISTRY = "https://registry.npmjs.org/" 

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
